/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Control.*;
/**
 *
 * @author juan
 */
public class Principal extends javax.swing.JFrame {
    private static Controlador miControl;

    /**
     * Creates new form Principal
     */
    public Principal() {
        miControl=new Controlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenAdmin = new javax.swing.JMenu();
        jMenAreas = new javax.swing.JMenuItem();
        JMniCargos = new javax.swing.JMenuItem();
        jMniEmpleados = new javax.swing.JMenuItem();
        jMnICursos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnIGranjas = new javax.swing.JMenuItem();
        jMnIGalpones = new javax.swing.JMenuItem();
        jMnIEventosGalpones = new javax.swing.JMenuItem();
        jMnILote = new javax.swing.JMenuItem();
        jMnIGallinas = new javax.swing.JMenuItem();
        jMnIVacunas = new javax.swing.JMenuItem();
        jMnITratamientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jMenAdmin.setText("Administracion");
        jMenAdmin.setToolTipText("");

        jMenAreas.setText("Areas");
        jMenAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenAreasActionPerformed(evt);
            }
        });
        jMenAdmin.add(jMenAreas);

        JMniCargos.setText("Cargos");
        JMniCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMniCargosActionPerformed(evt);
            }
        });
        jMenAdmin.add(JMniCargos);

        jMniEmpleados.setText("Empleados");
        jMniEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniEmpleadosActionPerformed(evt);
            }
        });
        jMenAdmin.add(jMniEmpleados);

        jMnICursos.setText("Cursos");
        jMnICursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnICursosActionPerformed(evt);
            }
        });
        jMenAdmin.add(jMnICursos);

        jMenuBar1.add(jMenAdmin);

        jMenu2.setText("Produccion");

        jMnIGranjas.setText("Granjas");
        jMnIGranjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIGranjasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnIGranjas);

        jMnIGalpones.setText("Galpones");
        jMnIGalpones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIGalponesActionPerformed(evt);
            }
        });
        jMenu2.add(jMnIGalpones);

        jMnIEventosGalpones.setText("Eventos Galpones");
        jMnIEventosGalpones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIEventosGalponesActionPerformed(evt);
            }
        });
        jMenu2.add(jMnIEventosGalpones);

        jMnILote.setText("Lotes");
        jMnILote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnILoteActionPerformed(evt);
            }
        });
        jMenu2.add(jMnILote);

        jMnIGallinas.setText("Gallinas");
        jMnIGallinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIGallinasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnIGallinas);

        jMnIVacunas.setText("Vacunas");
        jMnIVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIVacunasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnIVacunas);

        jMnITratamientos.setText("Tratamientos");
        jMnITratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnITratamientosActionPerformed(evt);
            }
        });
        jMenu2.add(jMnITratamientos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenAreasActionPerformed
        AreaVista a = new AreaVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show(); 
        
    }//GEN-LAST:event_jMenAreasActionPerformed

    private void jMnICursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnICursosActionPerformed
        // TODO add your handling code here:
         CursoVista a = new CursoVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnICursosActionPerformed

    private void jMnIGranjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIGranjasActionPerformed
        // TODO add your handling code here:
        GranjaVista a = new GranjaVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show(); 
    }//GEN-LAST:event_jMnIGranjasActionPerformed

    private void JMniCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMniCargosActionPerformed
        // TODO add your handling code here:
        CargoVista a = new CargoVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show(); 
        
    }//GEN-LAST:event_JMniCargosActionPerformed

    private void jMniEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniEmpleadosActionPerformed
        // TODO add your handling code here:
        EmpleadoVista a = new EmpleadoVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show(); 
    }//GEN-LAST:event_jMniEmpleadosActionPerformed

    private void jMnITratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnITratamientosActionPerformed
        TratamientoVista a = new TratamientoVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnITratamientosActionPerformed

    private void jMnIGalponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIGalponesActionPerformed
        GalponVista a = new GalponVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnIGalponesActionPerformed

    private void jMnIEventosGalponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIEventosGalponesActionPerformed
       EventoGalponVista a = new EventoGalponVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnIEventosGalponesActionPerformed

    private void jMnILoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnILoteActionPerformed
       LoteVista a = new LoteVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnILoteActionPerformed

    private void jMnIGallinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIGallinasActionPerformed
        GallinaVista a = new GallinaVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnIGallinasActionPerformed

    private void jMnIVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIVacunasActionPerformed
         VacunaVista a = new VacunaVista(this.miControl);
        this.jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_jMnIVacunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMniCargos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenAdmin;
    private javax.swing.JMenuItem jMenAreas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnICursos;
    private javax.swing.JMenuItem jMnIEventosGalpones;
    private javax.swing.JMenuItem jMnIGallinas;
    private javax.swing.JMenuItem jMnIGalpones;
    private javax.swing.JMenuItem jMnIGranjas;
    private javax.swing.JMenuItem jMnILote;
    private javax.swing.JMenuItem jMnITratamientos;
    private javax.swing.JMenuItem jMnIVacunas;
    private javax.swing.JMenuItem jMniEmpleados;
    // End of variables declaration//GEN-END:variables
}
